config/routes.rb
Rails.application.routes.draw do

	root 'daily_plans#show'
  resources :daily_plans
  resources :items, only: [:index]

end

app/models/daily_plan.rb
class DailyPlan < ActiveRecord::Base
  has_and_belongs_to_many :items
	validates_associated :items
	accepts_nested_attributes_for :items
	#TODO BUG: only validates items when updating, and not on create
	
	def total_protein
		items.all.inject(0) do |sum, item|
			sum += item.total_protein
		end
	end

	def total_calories
		items.all.inject(0) do |sum, item|
			sum += item.total_calories
		end
	end

	#TODO need to test
	def item_names
		names = []
		items.all.each do |item|
			names.push(item.name)
		end
		names
		#TODO refactor!
	end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :daily_plans
	validates_presence_of :quantity, if: :part_of_plan?
	validates :protein, :calories, :fat, :unit_quantity,
																	numericality: {greater_than_or_equal_to: 0}
	validates_numericality_of :quantity, greater_than_or_equal_to: 0, allow_nil: true

	def total_protein
		protein * (quantity / 100)
	end

	def total_calories
		calories * (quantity / 100)
	end

	def units
		quantity ? quantity / unit_quantity : nil
	end

	def set_units
	end

	def part_of_plan?
		daily_plans.all.any?
		# associated plans must be persisted to the DB
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daily_plans_controller.rb
class DailyPlansController < ApplicationController

  def show
		@plan = DailyPlan.take
    #TODO Change this to either use params id
    # or to look for plan with 'main' or 
    # 'current' attribute
  end

	def update
		@plan = DailyPlan.find(params[:id])
		if params.has_key?(:items)
			params[:items].each do |key, value|
				key = key.gsub('-', ' ')
				@plan.items.where({name: key}).take.update(quantity: value)
			end
		end
		#redirect_to daily_plan_path(params[:id])
		redirect_to root_path
		# TODO ajax
		# TODO refactor?
	end

	private

	def category_params
		params.require(:items).permit(@plan.item_names)
		#params.require(:items).tap do |whitelisted|
			#whitelisted[:items] = params[:user
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #respond_to :html, :js

  def index
    @items = Item.all
    respond_to do |format|
      format.js 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/daily_plans/show.html.erb
<h1>Daily plan goes here</h1>
<%= form_tag("/daily_plans/#{@plan.id}", method: :patch) do %>
	<table class="daily-plan"> <%# Add -table? %>
    <thead> <%# TODO Check whether this is commonly used %>
      <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th class="protein-col">Protein</th>
        <th>Calories</th>
      </tr>
    </thead>
    <tbody>
    <% @plan.items.each do |item| %>
      <% @item = item; item_name = item.name.squish.gsub(' ', '-')%>
      <tr class="food-item" id="<%= item_name %>">
        <td>
          <%= number_field(:item, :quantity, min: 0, name: "items[#{item_name}]", id: "#{item_name}-quantity") %>
        </td>
        <td class="name-col">    <%= item.name %>                   </td>
        <td class="protein-col"> <%= item.total_protein.round(2) %> </td>
        <td class="calories-col"><%= item.total_calories.round(2) %></td>
      </tr>
    <% end %>
    <%# Use tfoot for totals row? %>
      <tr class="totals-row">
        <td></td>
        <td></td>
        <td id="protein-total"> <em><%= @plan.total_protein.round(0) %></em> <small>g</small></td>
        <td id="calories-total"> 
          <em><%= @plan.total_calories.round(0) %></em> <small>kCal</small>
        </td>
      </tr>
    </tbody>
	</table>
	<%= submit_tag("Save") %>
<% end %>
<%= link_to "All items", items_path, remote: true %>
<section id="item-index"></section>
  

app/views/items/_index.html.erb
<h2>Items</h2>
<table>
<% @items.each do |item| %>
  <tr>
    <td><%= item.unit_quantity %></td>
    <td><%= item.name %></td>
    <td><%= item.protein %></td>
    <td><%= item.fat %></td>
    <td><%= item.calories %></td>
  </tr>
<% end %>
</table>
  

app/views/items/index.js.erb
<% logger.debug 'javascript running...' %>
$('#item-index').show();
$('#item-index').html("<%= j(render('index')) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<br />
<br />
<br />
<%= debug(params) if Rails.env.development? %>
<%= params.inspect %>

</body>
</html>